permalink: /:categories/:title/
url: "https://show1po.github.io/"
full_name: "Computer medication"
first_name: "Just"
last_name: "Me"
blog_title: "Show's Blog."
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "show"
copyright_year: "2016.10"
google_analytics_code: ""
aboutme: ""
